#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tenants.Demo2.Views.Shared
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.4.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_CustomLayout.cshtml")]
    public partial class CustomLayout : System.Web.Mvc.WebViewPage<RazorMultiTenancy.BaseViewModel>
    {
        public CustomLayout()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Shared\_CustomLayout.cshtml"
  
    Layout = null;
    var tenant = Model.Tenant;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n\r\n<html>\r\n<head>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(" />\r\n</head>\r\n<body>\r\n");

            
            #line 15 "..\..\Views\Shared\_CustomLayout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\_CustomLayout.cshtml"
     if(tenant.Languages.Count() > 1){
        foreach (var lang in tenant.Languages)
        {
            
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\_CustomLayout.cshtml"
       Write(Html.ActionLink(ViewRes.PageStaticText.ResourceManager.GetString(lang.ToString()), "Change", "Culture", new { lang = lang.ToString(), returnUrl = this.Request.RawUrl }, new { style = "margin-right: 10px;"}));

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\_CustomLayout.cshtml"
                                                                                                                                                                                                                           ;
        }
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n    <h1>");

            
            #line 22 "..\..\Views\Shared\_CustomLayout.cshtml"
   Write(tenant.Name);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n    \r\n");

WriteLiteral("    ");

            
            #line 24 "..\..\Views\Shared\_CustomLayout.cshtml"
Write(ViewRes.PageStaticText.LayoutAssembly);

            
            #line default
            #line hidden
WriteLiteral(" : Demo2 Module<br />\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 26 "..\..\Views\Shared\_CustomLayout.cshtml"
   Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
